#!/usr/bin/env python3
"""Bundle the harness for the browser, from the one source of truth.

The page runs the real analyzer rather than a JavaScript restatement of it. That
is not a purity argument: the hand-written checker already on this page shipped
a bug the Python side never had, because two implementations of one idea drift
the moment either is touched. Compiling the canonical code to WASM removes the
second implementation entirely.

This writes `harness-bundle.js`, a plain JS object of module sources plus the
registry data, and a digest over all of it. `tests/test_bundle.py` recomputes
that digest from `harness/` and fails if it moved, so a stale bundle is a red
test rather than a page quietly serving last week's logic.

Run after changing anything under harness/cacheeconomics:

    python3 web/build_bundle.py
"""

from __future__ import annotations

import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PKG = os.path.join(ROOT, "harness", "cacheeconomics")
REGISTRY = os.path.join(PKG, "data")
OUT = os.path.join(HERE, "harness-bundle.js")

# The recorder is excluded: it opens files, fsyncs and takes locks, none of
# which mean anything in a browser tab, and shipping it would advertise a
# capability the page does not have. The body segmenter is included, because the
# page offers to segment logged request bodies and could not -- it was not in
# the bundle at all, so that offer was false.
# recorder.py stays out: it opens files, fsyncs and takes locks, none of which
# mean anything in a tab. segment.py carries the pure request-shape logic both
# it and the body adapter use, which is exactly what the browser needs.
# plugin.py stays out for the same reason and one more: it is a server-side
# gateway integration, and it reaches for LiteLLM's CustomLogger when that
# package is installed. Neither belongs in a browser tab, and the third-party
# import would break the bundle's standard-library-only guarantee.
# cli.py and __main__.py join them: a command-line entry point means nothing in a
# browser tab, and argparse reading sys.argv in a Worker is a capability the page
# does not have. Excluding them also keeps the bundle's standard-library-only
# check honest rather than widening its allow-list to accommodate a module the
# page never imports.
EXCLUDE = {"recorder.py", "plugin.py", "cli.py", "__main__.py"}
ADAPTERS = {"bodies.py", "__init__.py"}


def sources() -> dict:
    out = {}
    for name in sorted(os.listdir(PKG)):
        if not name.endswith(".py") or name in EXCLUDE:
            continue
        with open(os.path.join(PKG, name)) as f:
            out[f"cacheeconomics/{name}"] = f.read()
    adapters = os.path.join(PKG, "adapters")
    for name in sorted(os.listdir(adapters)):
        if name not in ADAPTERS:
            continue
        with open(os.path.join(adapters, name)) as f:
            out[f"cacheeconomics/adapters/{name}"] = f.read()
    for name in sorted(os.listdir(REGISTRY)):
        if not name.endswith(".json"):
            continue
        with open(os.path.join(REGISTRY, name)) as f:
            out[f"cacheeconomics/data/{name}"] = f.read()
    return out


def digest(files: dict) -> str:
    h = hashlib.sha256()
    for path in sorted(files):
        h.update(path.encode())
        h.update(b"\0")
        h.update(files[path].encode())
        h.update(b"\0")
    return h.hexdigest()


def build() -> tuple[str, dict]:
    files = sources()
    body = (
        "// Generated by web/build_bundle.py. Do not edit.\n"
        "// Sources are copied verbatim from harness/; tests/test_bundle.py fails\n"
        "// if this file drifts from them.\n"
        f"export const BUNDLE_DIGEST = {json.dumps(digest(files))};\n"
        f"export const BUNDLE = {json.dumps(files, indent=0)};\n"
    )
    return body, files


def main() -> int:
    body, files = build()
    with open(OUT, "w") as f:
        f.write(body)
    size = len(body.encode())
    print(f"wrote {OUT}")
    print(f"  {len(files)} files, {size/1024:.0f} KB, digest {digest(files)[:16]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
